### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by wdog** [bcse/tw5-material-theme#1]
hello 

How can I install this theme in my TW5? Can you show me the the right procedure?

thanks

**Comment by bcse** [comment]
1. Go to https://bcse.github.io/tw5-material-theme/#%24%3A%2FControlPanel
1. Go to "Plugins" tab
1. Drag Material theme and drop into your TiddlyWiki (Only TiddlyWiki 5.1.4 or earlier are supported)
1. Import tiddler
1. Save and reload your TiddlyWiki
1. Now you can go to Control Panel and use this theme
