### ISSUE TITLE
Please put a link to install in tiddlywiki

### ISSUE THREAD

**Issue by somenxavier** [bcse/tw5-material-theme#3]
Just drag and drop

**Comment by bcse** [comment]
You can get it here: http://bcse.tw/tw5-material-theme/#%24%3A%2FControlPanel
But this theme is not compatible with latest TiddlyWiki.

**Comment by somenxavier** [comment]
Where?

**Comment by bcse** [comment]
<img width="724" alt="2018-01-05 9 32 26" src="https://user-images.githubusercontent.com/11269/34591871-6cd7c7c2-f1fb-11e7-8652-153d45a3e981.png">
